name: oauth_test
description: Sample project to test gotrue OAuth flow

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.2
  sign_in_with_apple: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
